### ISSUE TITLE
The settings of this extension can't be displayed

### ISSUE THREAD

**Issue by JadeVane** [lucaskenda/handyscripts2#1]
It was the first time I installed this extension, I looked forward to being able to use this plugin, But just get this error when I attempted to get in the settings interface.

Those information may be helpful:

- error message:

> The settings of extension handyscripts2@lucaskenda.com.ar had an error:
> ```
> ReferenceError: global is not defined
> ```
> 
> Stack trace:
> ```
> @/home/wenjinyu/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar/prefs.js:19:3
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> start@resource:///org/gnome/gjs/modules/script/package.js:206:5
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

system: `Ubuntu 20.04`
gnome-shell: `3.36.1`

**Comment by lucaskenda** [comment]
Hi!

It's a known issue and I've already sent the fix to https://extensions.gnome.org but they are still reviewing it. Meanwhile you can try this:

1. `vi /home/wenjinyu/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar/prefs.js` 

2. Comment the lines 18,19,20:

![image](https://user-images.githubusercontent.com/4048688/81476939-23ab6a80-91eb-11ea-9e97-da2e0f82ea7c.png)

3. Press **Alt + F2** and enter **r** in the input box. This command will reset the gnome shell.

This piece of code was used in the first version to get the path of the script folder but now I'm not using it anymore.

**Comment by JadeVane** [comment]
@lucaskenda It works! And the MOST important thing is, thank you for making this amazing extension, just perfect.
