### ISSUE TITLE
Unable to open directory if it contains spaces

### ISSUE THREAD

**Issue by CristianKerr** [lucaskenda/handyscripts2#3]
If I name my folder for scripts e.g. "Quick Scripts" and try to open it from the dropdown menu (scripts), the file browser shows error that it is unable to find it. But if I remove the space "QuickScripts" then it works.
On Ubuntu 20.10 with Nautilus as file browser.

**Comment by lucaskenda** [comment]
I've fixed the bug and submitted it to gnome shell extensions. Can you check the latest version if it works fine?
Thanks!

**Comment by CristianKerr** [comment]
Thank you. The folder with spaces now works. But the extension now doesn't run any script in that folder (spaces or no spaces). I click it but nothing happens.
