### ISSUE TITLE
Terminal doesn't open anymore

### ISSUE THREAD

**Issue by Maritsu** [lucaskenda/handyscripts2#4]
So this extension is great, but starting yesterday if I ran *any* script, the terminal just wouldn't open. Using latest version from [GNOME Extensions](https://extensions.gnome.org), even tried reinstalling, still doesn't work.

**Comment by Maritsu** [comment]
## UPDATE

When trying to open the extension's settings, I got this error:

---
```
ReferenceError: TERMINAL_COMMAND is not defined
```

Stack trace:
```
buildPrefsWidget@/home/bittheprotogen/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar/prefs.js:70:1
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by lucaskenda** [comment]
Hi! Can you try running **Alt + F2**, then in run command enter **r** to restart gnome shell service, then try again.

**Comment by Maritsu** [comment]
Just did, still happens. Same error.

![Settings window should be here](https://user-images.githubusercontent.com/66056347/115558140-b89b5c80-a2b2-11eb-82f4-e3b18c77e592.png)

**Comment by lucaskenda** [comment]
This is strange.. can you execute:
```
cd $HOME/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar/schemas
cat org.gnome.shell.extensions.handyscripts.gschema.xml | grep terminal-command

```
```
cd $HOME/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar
cat prefs.js | grep command
```

And send me the output.

**Comment by hpschlenvoigt** [comment]
Hi,
I have the same original issue since a few days: The extension does not run any script. Alt+F2 and r did not work, so I started looking if there are some updates available, and finally ended here. Still, I can open the settings dialog.

Running what you said above yields:
`<key name="terminal-command" type="s">`
and
`const BASH_COMMMAND = "bash-command";
const PYTHON_COMMMAND = "python-command";
const TERMINAL_COMMAND = "terminal-command";
    _("Enable/Disable pause command to keep the script terminal alive.")
    _("Bash command"),
    _("Python command"),
`

**Comment by lucaskenda** [comment]
@hpschlenvoigt I think you have another issue. Can you show your tweak settings?

**Comment by arrabida** [comment]
Hi,
I have exactly the same problem with the same asked output.

**Comment by Maritsu** [comment]
> This is strange.. can you execute:
> 
> ```
> cd $HOME/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar/schemas
> cat org.gnome.shell.extensions.handyscripts.gschema.xml | grep terminal-command
> ```
> 
> ```
> cd $HOME/.local/share/gnome-shell/extensions/handyscripts2@lucaskenda.com.ar
> cat prefs.js | grep command
> ```
> 
> And send me the output.

@lucaskenda The first output is
```
<key name="terminal-command" type="s">
```
and the second one is
```//const BASH_COMMMAND = "bash-command";
//const PYTHON_COMMMAND = "python-command";
//const TERMINAL_COMMAND = "terminal-command";
    _("Enable/Disable pause command to keep the script terminal alive.")
    _("Bash command"),
    _("Python command"),
```

**Comment by lucaskenda** [comment]
@Maritsu your problem is that you have commented some variables:

`
//const PYTHON_COMMMAND = "python-command";
`
`
//const TERMINAL_COMMAND = "terminal-command";
`

So you have a modified version. Your prefs.js file must be like this: https://raw.githubusercontent.com/lucaskenda/handyscripts2/master/prefs.js

**Comment by Maritsu** [comment]
Nope, even after GNOME restart terminal doesn't open.

**Comment by lucaskenda** [comment]
@Maritsu its really strange that you have commented lines, this is not part of the code.

The error you have is because you are not initializing the variable: 
`ReferenceError: TERMINAL_COMMAND is not defined`
`//const TERMINAL_COMMAND = "terminal-command";`

**Comment by Maritsu** [comment]
The point is, I haven't

**Comment by lucaskenda** [comment]
Now can you show me your tweak settings?

**Comment by Maritsu** [comment]
![Extension settings](https://user-images.githubusercontent.com/66056347/115719588-87875e80-a37c-11eb-963c-dc823f3e46b5.png)

**Comment by Maritsu** [comment]
oh ok! so I have to add `--` at the end?

**Comment by lucaskenda** [comment]
yes

**Comment by Maritsu** [comment]
Ok, thank you!

**Comment by hpschlenvoigt** [comment]
Indeed, adding the "--" at the Gnome terminal, it works again.
Thank you all.

**Comment by sergiocodes** [comment]
Thank you @lucaskenda, adding "--" solved the problem.

**Comment by CristianKerr** [comment]
Hi @lucaskenda I had the same problem, adding -- solved it for me too, but I haven't modified this field in the past, so maybe it would be nice to have it there by default.

**Comment by anohren** [comment]
This fixed it. Good thing I looked through closed issues. Would've been nice if issues could be pinned on github

**Comment by coddingtonbear** [comment]
Just by the way, @lucaskenda, I think this might've gotten lost above, but the default settings for a fresh installation do not include the required `--`; so the plugin won't quite work out-of-the-box.  If you'd like a PR, though, I'd be glad to put one together addressing that.

**Comment by lucaskenda** [comment]
@coddingtonbear yes, just send a PR! Next time I'll try to check the plugin in a fresh VM before submitting to GNOME Shell Extensions. Thanks!
